#include <genesis.h>
#include "colors.h"


const u8 dark_col_lut[16] = {
  0, GREEN_IDX,      RED_IDX,      BLUE_IDX,      BROWN_IDX,      STEEL_IDX,
     DARK_GREEN_IDX, DARK_RED_IDX, DARK_BLUE_IDX, DARK_BROWN_IDX, DARK_STEEL_IDX,
     DARK_GREEN_IDX, DARK_RED_IDX, DARK_BLUE_IDX, DARK_BROWN_IDX, DARK_STEEL_IDX
};

const u8 light_col_lut[16] = {
  0, LIGHT_GREEN_IDX, LIGHT_RED_IDX, LIGHT_BLUE_IDX, LIGHT_BROWN_IDX, LIGHT_STEEL_IDX,
     LIGHT_GREEN_IDX, LIGHT_RED_IDX, LIGHT_BLUE_IDX, LIGHT_BROWN_IDX, LIGHT_STEEL_IDX,
     GREEN_IDX,      RED_IDX,      BLUE_IDX,      BROWN_IDX,      STEEL_IDX,
};


#define PIX(p) ((p << 4) | p)
#define DPIX(p,q) ((p << 4) | q)

// dark dist is -2 brightness
// mid dist is -1 brightness
// -2 is negative 2, etc

const u8 color_calc_table[16*5*3] = {
//const u8 dark_dist_lut[16*5] = {
  // -2
  0, PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // -1
  0, PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 0
  0, PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 1
  0, PIX(GREEN_IDX), PIX(RED_IDX), PIX(BLUE_IDX), PIX(BROWN_IDX), PIX(STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 2
  0, PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
     PIX(GREEN_IDX), PIX(RED_IDX), PIX(BLUE_IDX), PIX(BROWN_IDX), PIX(STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
//};

//const u8 mid_dist_lut[16*5] = {
  // -2
  0, PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // -1
  0, DPIX(GREEN_IDX,DARK_GREEN_IDX), DPIX(RED_IDX,DARK_RED_IDX), DPIX(BLUE_IDX, DARK_BLUE_IDX), DPIX(BROWN_IDX, DARK_BROWN_IDX), DPIX(STEEL_IDX, DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 0
  0, DPIX(LIGHT_GREEN_IDX, GREEN_IDX), DPIX(LIGHT_RED_IDX, RED_IDX), DPIX(LIGHT_BLUE_IDX, BLUE_IDX), DPIX(LIGHT_BROWN_IDX, BROWN_IDX), DPIX(LIGHT_STEEL_IDX, STEEL_IDX),
     DPIX(GREEN_IDX,DARK_GREEN_IDX), DPIX(RED_IDX,DARK_RED_IDX), DPIX(BLUE_IDX, DARK_BLUE_IDX), DPIX(BROWN_IDX, DARK_BROWN_IDX), DPIX(STEEL_IDX, DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX),  PIX(DARK_RED_IDX),  PIX(DARK_BLUE_IDX),  PIX(DARK_BROWN_IDX),  PIX(DARK_STEEL_IDX),
  // 1
  0, DPIX(LIGHT_GREEN_IDX, GREEN_IDX), DPIX(LIGHT_RED_IDX, RED_IDX), DPIX(LIGHT_BLUE_IDX, BLUE_IDX), DPIX(LIGHT_BROWN_IDX, BROWN_IDX), DPIX(LIGHT_STEEL_IDX, STEEL_IDX),
     DPIX(LIGHT_GREEN_IDX, GREEN_IDX), DPIX(LIGHT_RED_IDX, RED_IDX), DPIX(LIGHT_BLUE_IDX, BLUE_IDX), DPIX(LIGHT_BROWN_IDX, BROWN_IDX), DPIX(LIGHT_STEEL_IDX, STEEL_IDX),
     DPIX(GREEN_IDX,DARK_GREEN_IDX), DPIX(RED_IDX,DARK_RED_IDX), DPIX(BLUE_IDX, DARK_BLUE_IDX), DPIX(BROWN_IDX, DARK_BROWN_IDX), DPIX(STEEL_IDX, DARK_STEEL_IDX),
  // 2
  0, DPIX(LIGHT_GREEN_IDX, GREEN_IDX), DPIX(LIGHT_RED_IDX, RED_IDX), DPIX(LIGHT_BLUE_IDX, BLUE_IDX), DPIX(LIGHT_BROWN_IDX, BROWN_IDX), DPIX(LIGHT_STEEL_IDX, STEEL_IDX),
     DPIX(LIGHT_GREEN_IDX, GREEN_IDX), DPIX(LIGHT_RED_IDX, RED_IDX), DPIX(LIGHT_BLUE_IDX, BLUE_IDX), DPIX(LIGHT_BROWN_IDX, BROWN_IDX), DPIX(LIGHT_STEEL_IDX, STEEL_IDX),
     DPIX(LIGHT_GREEN_IDX, GREEN_IDX), DPIX(LIGHT_RED_IDX, RED_IDX), DPIX(LIGHT_BLUE_IDX, BLUE_IDX), DPIX(LIGHT_BROWN_IDX, BROWN_IDX), DPIX(LIGHT_STEEL_IDX, STEEL_IDX),
//};

//const u8 near_dist[16*5] = {
  // -2
  0, PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // -1
  0, PIX(GREEN_IDX), PIX(RED_IDX), PIX(BLUE_IDX), PIX(BROWN_IDX), PIX(STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 0
  0, PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
     PIX(GREEN_IDX), PIX(RED_IDX), PIX(BLUE_IDX), PIX(BROWN_IDX), PIX(STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 1
  0, PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
     PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
     PIX(DARK_GREEN_IDX), PIX(DARK_RED_IDX), PIX(DARK_BLUE_IDX), PIX(DARK_BROWN_IDX), PIX(DARK_STEEL_IDX),
  // 2
  0, PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
     PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
     PIX(LIGHT_GREEN_IDX), PIX(LIGHT_RED_IDX), PIX(LIGHT_BLUE_IDX), PIX(LIGHT_BROWN_IDX), PIX(LIGHT_STEEL_IDX),
};

u8 get_dark_color(u8 col_idx, s8 light_level) {
  u16 light_off = (light_level+2)<<4;
  return color_calc_table[light_off+col_idx];
}

u8 get_mid_dark_color(u8 col_idx, s8 light_level) {
  u16 light_off = (light_level+2)<<4;  
  u16 dist_off = (16*5);
  return color_calc_table[light_off+dist_off+col_idx];
}

u8 get_light_color(u8 col_idx, s8 light_level) {
  u16 light_off = (light_level+2)<<4;  
  u16 dist_off = (16*5*2);
  return color_calc_table[light_off+dist_off+col_idx];
}

u8 calculate_color(u8 col_idx, u32 dist, s8 light_level) {
  u16 light_off = (light_level+2)<<4;
  u16 dist_off = (dist >= DARK_DIST) ? 0 : (dist >= MID_DARK_DIST) ? (16*5) : (16*5*2);

  return color_calc_table[light_off+dist_off+col_idx];
}


u8 needs_dither(u32 dist) {
  if(dist >= DARK_DIST) {
    return 0;
  } else if (dist >= MID_DARK_DIST) {
    return 1;
  } else if (dist >= MID_DIST) {
    return 0;
  } else {
    return 1;
  }
}