name: Build editor exe with Pyinstaller

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src/python/editor

    - name: Copy config file
      run: sudo cp src/python/editor/conf.ini src/python/editor/dist/windows/conf.ini

    - name: Copy engine binary
      run: sudo cp built_rom.bin src/python/editor/dist/windows/rom.bin

    - uses: actions/upload-artifact@v2
      with:
        name: portal-editor
        path: src/python/editor/dist/windows/*
