name: Build editor exe with Pyinstaller

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src/python/editor

    - name: Print directory
      run: ls -R ./

    - name: Tar files
      run: tar -cvf editor.tar ./dist/windows

    - uses: actions/upload-artifact@v2
      with:
        name: portal-editor
        path: editor.tar
