name: Build editor exe with Pyinstaller

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add path
      run: export PATH=src/python/editor/DLLs:$PATH  

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src/python/editor

    - name: Copy config file
      run: sudo cp src/python/editor/build_conf.ini src/python/editor/dist/windows/conf.ini

    - name: Copy readme
      run: sudo cp src/python/editor/README src/python/editor/dist/windows/README

    - name: Copy engine binary
      run: sudo cp built_rom.bin src/python/editor/dist/windows/rom.bin

    - name: Create textures directory
      run: sudo mkdir src/python/editor/dist/windows/textures

    - name: Create sprites directory
      run: sudo mkdir src/python/editor/dist/windows/sprites

    - name: Create music directory
      run: sudo mkdir src/python/editor/dist/windows/music

    - uses: actions/upload-artifact@v2
      with:
        name: portal-editor
        path: src/python/editor/dist/windows/*
